AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'wasthebomright-app

  SAM Template for wasthebomright-app

  '
Globals:
  Function:
    Timeout: 30
Resources:
  ObsMinFunctionDocker:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 489446838335.dkr.ecr.ap-southeast-2.amazonaws.com/wasthebomright:latest
      ImageConfig:
        EntryPoint:
        - python
        - -m
        - awslambdaric
        Command:
        - app.obs_min_lambda
      AutoPublishAlias: live
      Policies:
      - AWSLambdaExecute
      Events:
        DailyTimer:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *)
    Metadata:
      SamResourceId: ObsMinFunctionDocker
