AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wasthebomright-app

  SAM Template for wasthebomright-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ObsMinFunctionDocker:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 489446838335.dkr.ecr.ap-southeast-2.amazonaws.com/wasthebomright:latest
      ImageConfig:
        EntryPoint:
          - 'python'
          - '-m'
          - 'awslambdaric'
        Command:
          - 'app.obs_min_lambda'
      AutoPublishAlias: live
      Policies:
        - AWSLambdaExecute
      Events:
        DailyTimer:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 * * ? *) # 9AM MEL time
  # ObsMaxFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: build/
  #     Handler: app.obs_max_lambda
  #     Runtime: python3.9
  #     AutoPublishAlias: live
  #     Policies:
  #       - AWSLambdaExecute
  #     Architectures:
  #       - x86_64
  #     Events:
  #       DailyTimer:
  #         Type: Schedule
  #         Properties:
  #           Schedule: cron(45 9 * * ? *) # 8:45PM Mel time
  # ForecastsFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: build/
  #     Handler: app.forecasts_lambda
  #     Runtime: python3.9
  #     AutoPublishAlias: live
  #     Policies:
  #       - AWSLambdaExecute
  #     Architectures:
  #       - x86_64
  #     Events:
  #       DailyTimer:
  #         Type: Schedule
  #         Properties:
  #           Schedule: cron(30 4 * * ? *) # 3:30PM Mel time
  # ImageGeneratorFunction:
  #   Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  #   Properties:
  #     CodeUri: build/
  #     Handler: app.image_generator_lambda
  #     Runtime: python3.9
  #     AutoPublishAlias: live
  #     Policies:
  #       - AWSLambdaExecute
  #     Architectures:
  #       - x86_64
