AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  wasthebomright-app

  SAM Template for wasthebomright-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  BomScraperFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/
      Handler: app.bom_scraper_lambda
      Runtime: python3.9
      AutoPublishAlias: live
      Policies:
        - AWSLambdaExecute
      Architectures:
        - x86_64
      Events:
        DailyTimer:
          Type: Schedule
          Properties:
            Schedule: cron(45 9 * * ? *)
  ImageGeneratorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/
      Handler: app.image_generator_lambda
      Runtime: python3.9
      AutoPublishAlias: live
      Policies:
        - AWSLambdaExecute
      Architectures:
        - x86_64
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: wasthebomright
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.json'
